# Generated by Django 5.1.7 on 2025-03-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_achievement_skill_skillcategory_timelineevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('achievement', 'Achievement'), ('milestone', 'Milestone'), ('education', 'Education'), ('experience', 'Experience')], default='achievement', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='TimelineEvent',
        ),
    ]
